theme: jekyll-theme-minimal
title: Homepage
description: Hi, and welcome to my GitHub page. This page is supposed to, and will very soon, contain information on my academic background.


logo: <img src="1.png">
